### ISSUE TITLE
Maybe include busted instead of lua unit

### ISSUE THREAD

**Issue by stijnbernards** [fikin/nodemcu-lua-mocks#2]
I thought it would be nice to use: https://olivinelabs.com/busted/
Instead of lua busted

**Comment by fikin** [comment]
if i'm not mistaken the code should allow either of rather than instead. if there are problems, i can look to fix them.

looking briefly at busted, it seems rather "large" compared to luaunit. i'm not sure it can bundled-in in this repo without luarocks, which i kind of walked away from some time in past ;)

imho adding examples with it to the documentation is perfectly ok for now.

**Comment by stijnbernards** [comment]
Yeah that's correct. Busted is quite a large framework. 

I will try to do that :)
